spring.application.name=revenant

# Conexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/revenant_db
spring.datasource.username=" "
spring.datasource.password=" "
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Documentacion y swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.model-converters.pageable-converter.enabled=true
springdoc.default-produces-media-type=application/json

# Seguridad
jwt.secret=""
jwt.expirationMs=00000
