spring.application.name=revenant
server.port=${PORT:8080}
# Conexion PostgreSQL
spring.datasource.url=${URL_DATABASE}
spring.datasource.username=${USER_DATABASE}
spring.datasource.password=${PASSWORD_DATABASE}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
# Dialecto PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Documentacion y swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.model-converters.pageable-converter.enabled=true
springdoc.default-produces-media-type=application/json

# Seguridad
jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS}