import { eventBus } from "@/game/events";
import type { AttackRequest } from "@/game/interfaces/AttackRequest";

/**
 * AttackRequestService forwards AttackRequests to the Combat System
 * via the Event Bus.
 *
 * Every valid attack — including those with an empty targets array —
 * is emitted as an ATTACK_REQUEST event so the CombatSystem can
 * process it.
 *
 * This service is stateless and reusable.
 */
export class AttackRequestService {
  /**
   * Forwards an AttackRequest to the Combat System by emitting
   * the ATTACK_REQUEST event on the Event Bus.
   *
   * The request is emitted regardless of whether the targets array
   * is empty. An attack with no detected enemies is still a valid
   * attack that the Combat System must acknowledge.
   *
   * @param request - The AttackRequest generated by the PlayerAttackSystem.
   */
  forward(request: AttackRequest): void {
    eventBus.emit("ATTACK_REQUEST", request);
  }
}
