import type { Player } from "@/game/entities/characters/Player";
import type { Enemy } from "@/game/entities/characters/Enemy";
import type { PlayerDirection } from "@/game/services/SpriteComposer";

/**
 * Represents an attack generated by the player.
 *
 * This interface serves as a data transfer object between the Player Attack system
 * and the Combat System. It contains only attack information required for combat resolution.
 *
 * The Combat System is responsible for interpreting this request and resolving damage,
 * enemy health changes, experience, and rewards.
 */
export interface AttackRequest {
  /** The player who initiated the attack. */
  attacker: Player;

  /** All enemies detected inside the attack hitbox. May be empty if no enemies are in range. */
  targets: Enemy[];

  /** The direction the player was facing when the attack was executed. */
  direction: PlayerDirection;

  /** The timestamp (in milliseconds) when the attack was executed. */
  timestamp: number;
}
