import type { Enemy } from "@/game/entities/characters/Enemy";

/**
 * Represents the result of resolving combat against a single target.
 *
 * Generated by the CombatSystem after processing each target in an AttackRequest.
 * All properties are readonly to ensure immutability after creation.
 */
export interface CombatResult {
  /** The enemy that was attacked. */
  readonly target: Enemy;

  /** The final damage dealt after armor reduction. Always non-negative. */
  readonly damage: number;

  /** The enemy's remaining health after damage was applied. Never negative. */
  readonly remainingHealth: number;

  /** Whether the enemy was defeated as a result of this attack. */
  readonly defeated: boolean;
}
