/**
 * Represents the result of a damage calculation.
 *
 * Generated by the DamageCalculator after computing the final damage
 * dealt to a target. All properties are readonly to ensure immutability.
 */
export interface DamageCalculation {
  /** The attacker's raw attack value. */
  readonly attack: number;

  /** The target's armor value used for damage reduction. */
  readonly armor: number;

  /** The final damage after armor reduction. Always non-negative. */
  readonly finalDamage: number;
}
